[package]
name = "touying-simpl-whu"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["nowherechan"]
license = "MIT"
description = "武汉大学 Touying 幻灯片主题 (Touying Slide Theme for WHU)"
repository = "https://github.com/Hithereland/touying-whu"
keywords = ["touying", "slide", "whu"]
categories = ["presentation"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
